version: "3"
services:
  ollama-serve:
    container_name: ollama-serve
    build:
      context: .
      target: ollamallm
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ~/ollama:/root/.ollama
    networks:
      - opensearch-net
    stdin_open: true
    tty: true
  local-stack:
    container_name: local-stack
    image: localstack/localstack
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - opensearch-net
    stdin_open: true
    tty: true
  local-stack-setup:
    container_name: local-stack-setup
    build:
      context: .
      target: local-stack-setup
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      local-stack:
        condition: service_healthy
      uvicorn_app:
        condition: service_healthy
    networks:
      - opensearch-net
    stdin_open: true
    tty: true
  uvicorn_app:
    container_name: uvicorn_app
    build:
      context: .
      target: ecsopensearch
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/docs" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    networks:
      - opensearch-net
    stdin_open: true  # Equivalent to -it
    tty: true
    depends_on:
      opensearch-node:
        condition: service_healthy
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge
